"""
fx_catalog.py — Forenstix-2.0 tool registry

Defines every tool available through the plugin.  Tools are grouped into
categories.  Each :class:`Tool` carries enough metadata for fx_run.py to
execute it in the right backend and for Claude to pick the right tool for a
given task.

Reliability legend
  green  — plug-and-play; runs in Docker/native without fuss
  yellow — depends on backend, hardware, or sudo config

Flag vocabulary
  sudo        needs elevated privileges on native/WSL
  interactive requires a TTY / interactive session
  long        typically runs for minutes
  hw          requires physical hardware (WiFi adapter, Bluetooth, etc.)
  gui         launches a graphical UI
  archived    upstream project is no longer maintained
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class Tool:
    id: str                             # unique snake_case identifier
    name: str                           # human display name
    url: str                            # upstream repo / website
    category: str                       # category key
    description: str                    # one-line description
    install_cmd: str                    # native/WSL install command
    run_cmd: str                        # run template; {args} = user-supplied args
    docker_image: str = ""              # preferred Docker image; "" = kali fallback
    flags: List[str] = field(default_factory=list)
    reliability: str = "yellow"         # "green" | "yellow"
    aliases: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Category registry (ordered for README display)
# ---------------------------------------------------------------------------

CATEGORIES: Dict[str, str] = {
    "anon":        "🛡  Anonymously Hiding",
    "recon":       "🔍  Information Gathering",
    "wordlist":    "📚  Wordlist Generator",
    "wireless":    "📶  Wireless Attack",
    "sqli":        "🧩  SQL Injection",
    "phishing":    "🎣  Phishing Attack",
    "web":         "🌐  Web Attack",
    "postex":      "🔧  Post Exploitation",
    "forensics":   "🕵   Forensics",
    "payload":     "📦  Payload Creation",
    "exploit":     "🧰  Exploit Framework",
    "reveng":      "🔁  Reverse Engineering",
    "ddos":        "⚡  DDoS Attack",
    "rat":         "🖥   RAT",
    "xss":         "💥  XSS Attack",
    "stego":       "🖼   Steganography",
    "ad":          "🏢  Active Directory",
    "cloud":       "☁   Cloud Security",
    "mobile":      "📱  Mobile Security",
    "other":       "✨  Other Tools",
    # ── Forenstix-2.0 extras ──────────────────────────────────────────────
    "mem_forensics":  "🧠  Memory Forensics",
    "disk_forensics": "💾  Disk Forensics",
    "net_forensics":  "🌊  Network Forensics",
    "log_forensics":  "📋  Log Analysis & Threat Hunting",
    "malware":        "🦠  Malware Analysis",
    "timeline":       "⏱   Timeline Analysis",
}


# ---------------------------------------------------------------------------
# Tool definitions
# ---------------------------------------------------------------------------

TOOLS: List[Tool] = [

    # ── Anonymously Hiding ─────────────────────────────────────────────────
    Tool(
        id="anonsurf",
        name="Anonymously Surf",
        url="https://github.com/Und3rf10w/kali-anonsurf",
        category="anon",
        description="Route all traffic through Tor; wipe RAM on shutdown.",
        install_cmd="git clone https://github.com/Und3rf10w/kali-anonsurf && cd kali-anonsurf && sudo ./installer.sh",
        run_cmd="anonsurf {args}",
        flags=["sudo"],
    ),
    Tool(
        id="multitor",
        name="Multitor",
        url="https://github.com/trimstray/multitor",
        category="anon",
        description="Create multiple Tor instances for distributed anonymity.",
        install_cmd="git clone https://github.com/trimstray/multitor",
        run_cmd="bash multitor/bin/multitor {args}",
        flags=["sudo"],
    ),

    # ── Information Gathering ──────────────────────────────────────────────
    Tool(
        id="amass",
        name="Amass",
        url="https://github.com/owasp-amass/amass",
        category="recon",
        description="In-depth subdomain enumeration and attack surface mapping.",
        install_cmd="go install -v github.com/owasp-amass/amass/v4/...@master",
        run_cmd="amass enum -d {args}",
        docker_image="caffix/amass",
        reliability="green",
        aliases=["attack surface", "subdomain enum"],
    ),
    Tool(
        id="breacher",
        name="Breacher",
        url="https://github.com/s0md3v/Breacher",
        category="recon",
        description="Multithreaded admin panel finder.",
        install_cmd="git clone https://github.com/s0md3v/Breacher && pip3 install -r Breacher/requirements.txt",
        run_cmd="python3 Breacher/breacher.py {args}",
        flags=["interactive"],
    ),
    Tool(
        id="dracnmap",
        name="Dracnmap",
        url="https://github.com/Screetsec/Dracnmap",
        category="recon",
        description="nmap wrapper with exploit-oriented menus.",
        install_cmd="git clone https://github.com/Screetsec/Dracnmap",
        run_cmd="bash Dracnmap/Dracnmap.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="shodanfy",
        name="Find Info Using Shodan",
        url="https://github.com/m4ll0k/Shodanfy.py",
        category="recon",
        description="Get ports, vulns, banners from Shodan.",
        install_cmd="git clone https://github.com/m4ll0k/Shodanfy.py",
        run_cmd="python3 Shodanfy.py/shodanfy.py {args}",
    ),
    Tool(
        id="gitleaks",
        name="Gitleaks",
        url="https://github.com/gitleaks/gitleaks",
        category="recon",
        description="Fast secret scanner for git repos.",
        install_cmd="go install github.com/zricethezav/gitleaks/v8@latest",
        run_cmd="gitleaks {args}",
        docker_image="zricethezav/gitleaks",
        reliability="green",
        aliases=["secrets", "api keys", "credentials leak"],
    ),
    Tool(
        id="holehe",
        name="Holehe",
        url="https://github.com/megadose/holehe",
        category="recon",
        description="Check if an email address is registered on 120+ websites.",
        install_cmd="pip3 install holehe",
        run_cmd="holehe {args}",
        docker_image="megadose/holehe",
        reliability="green",
        aliases=["email osint", "account finder"],
    ),
    Tool(
        id="host_to_ip",
        name="Host to IP",
        url="",
        category="recon",
        description="Resolve hostname to IP address.",
        install_cmd="",
        run_cmd="python3 -c \"import socket; print(socket.gethostbyname('{args}'))\"",
        flags=["interactive"],
    ),
    Tool(
        id="httpx",
        name="httpx",
        url="https://github.com/projectdiscovery/httpx",
        category="recon",
        description="Fast multi-purpose HTTP probing tool.",
        install_cmd="go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest",
        run_cmd="httpx {args}",
        docker_image="projectdiscovery/httpx",
        reliability="green",
        aliases=["http probe", "web tech"],
    ),
    Tool(
        id="infoga",
        name="Infoga",
        url="https://github.com/m4ll0k/Infoga",
        category="recon",
        description="Gather email account info from public sources.",
        install_cmd="git clone https://github.com/m4ll0k/Infoga && pip3 install -r Infoga/requirements.txt",
        run_cmd="python3 Infoga/infoga.py {args}",
        reliability="green",
    ),
    Tool(
        id="isitdown",
        name="IsItDown",
        url="",
        category="recon",
        description="Check whether a website is online.",
        install_cmd="",
        run_cmd="python3 -c \"import urllib.request; urllib.request.urlopen('{args}'); print('UP')\"",
    ),
    Tool(
        id="maigret",
        name="Maigret",
        url="https://github.com/soxoj/maigret",
        category="recon",
        description="Username OSINT across 3000+ sites.",
        install_cmd="pip3 install maigret",
        run_cmd="maigret {args}",
        docker_image="soxoj/maigret",
        reliability="green",
        aliases=["username osint", "social hunt"],
    ),
    Tool(
        id="masscan",
        name="Masscan",
        url="https://github.com/robertdavidgraham/masscan",
        category="recon",
        description="Fastest internet port scanner — 10 M packets/sec.",
        install_cmd="apt-get install -y masscan",
        run_cmd="masscan {args}",
        docker_image="ilyaglow/masscan",
        flags=["sudo"],
        aliases=["port scan", "fast scan"],
    ),
    Tool(
        id="nmap",
        name="nmap",
        url="https://github.com/nmap/nmap",
        category="recon",
        description="Network discovery and security auditing.",
        install_cmd="apt-get install -y nmap",
        run_cmd="nmap {args}",
        docker_image="instrumentisto/nmap",
        flags=["sudo"],
        aliases=["network scan", "port scan"],
    ),
    Tool(
        id="rang3r",
        name="rang3r",
        url="https://github.com/floriankunushevci/rang3r",
        category="recon",
        description="Multi-threaded Python port scanner.",
        install_cmd="git clone https://github.com/floriankunushevci/rang3r",
        run_cmd="python3 rang3r/rang3r.py {args}",
        flags=["interactive"],
    ),
    Tool(
        id="recondog",
        name="ReconDog",
        url="https://github.com/s0md3v/ReconDog",
        category="recon",
        description="All-in-one recon suite.",
        install_cmd="git clone https://github.com/s0md3v/ReconDog && pip3 install -r ReconDog/requirements.txt",
        run_cmd="python3 ReconDog/dog.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="reconspider",
        name="ReconSpider",
        url="https://github.com/bhavsec/reconspider",
        category="recon",
        description="Advanced OSINT framework for IPs, emails, websites.",
        install_cmd="git clone https://github.com/bhavsec/reconspider && pip3 install -r reconspider/requirements.txt",
        run_cmd="python3 reconspider/reconspider.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="redhawk",
        name="RED HAWK",
        url="https://github.com/Tuhinshubhra/RED_HAWK",
        category="recon",
        description="All-in-one info-gathering and vuln scanning.",
        install_cmd="git clone https://github.com/Tuhinshubhra/RED_HAWK",
        run_cmd="php RED_HAWK/rhawk.php {args}",
        reliability="green",
    ),
    Tool(
        id="rustscan",
        name="RustScan",
        url="https://github.com/RustScan/RustScan",
        category="recon",
        description="Scans all 65k ports in 3 seconds, hands results to nmap.",
        install_cmd="cargo install rustscan",
        run_cmd="rustscan {args}",
        docker_image="rustscan/rustscan",
        flags=["sudo"],
        aliases=["fast port scan"],
    ),
    Tool(
        id="secretfinder",
        name="SecretFinder",
        url="https://github.com/m4ll0k/SecretFinder",
        category="recon",
        description="Find sensitive data (API keys, tokens) in JS files.",
        install_cmd="git clone https://github.com/m4ll0k/SecretFinder && pip3 install -r SecretFinder/requirements.txt",
        run_cmd="python3 SecretFinder/SecretFinder.py {args}",
        flags=["sudo"],
        aliases=["api key finder"],
    ),
    Tool(
        id="spiderfoot",
        name="SpiderFoot",
        url="https://github.com/smicallef/spiderfoot",
        category="recon",
        description="OSINT automation for threat intelligence and attack surface.",
        install_cmd="pip3 install spiderfoot",
        run_cmd="spiderfoot {args}",
        docker_image="spiderfoot/spiderfoot",
        reliability="green",
        aliases=["osint automation"],
    ),
    Tool(
        id="striker",
        name="Striker",
        url="https://github.com/s0md3v/Striker",
        category="recon",
        description="Recon and vulnerability scanning suite.",
        install_cmd="git clone https://github.com/s0md3v/Striker && pip3 install -r Striker/requirements.txt",
        run_cmd="python3 Striker/striker.py {args}",
        flags=["interactive"],
    ),
    Tool(
        id="subfinder",
        name="Subfinder",
        url="https://github.com/projectdiscovery/subfinder",
        category="recon",
        description="Fast passive subdomain enumeration.",
        install_cmd="go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        run_cmd="subfinder -d {args}",
        docker_image="projectdiscovery/subfinder",
        reliability="green",
        aliases=["subdomain"],
    ),
    Tool(
        id="theharvester",
        name="theHarvester",
        url="https://github.com/laramies/theHarvester",
        category="recon",
        description="Gather emails, subdomains, IPs from public sources.",
        install_cmd="pip3 install theHarvester",
        run_cmd="theHarvester {args}",
        docker_image="secsi/theharvester",
        reliability="green",
        aliases=["email harvest", "osint"],
    ),
    Tool(
        id="trufflehog",
        name="TruffleHog",
        url="https://github.com/trufflesecurity/trufflehog",
        category="recon",
        description="Find and verify leaked credentials in git repos, S3, filesystems.",
        install_cmd="pip3 install trufflehog",
        run_cmd="trufflehog {args}",
        docker_image="trufflesecurity/trufflehog",
        reliability="green",
        aliases=["secrets", "credentials leak"],
    ),
    Tool(
        id="xerosploit",
        name="Xerosploit",
        url="https://github.com/LionSec/xerosploit",
        category="recon",
        description="Penetration testing toolkit for MITM attacks.",
        install_cmd="git clone https://github.com/LionSec/xerosploit && cd xerosploit && sudo python3 install.py",
        run_cmd="sudo python3 xerosploit/xerosploit.py {args}",
        flags=["sudo"],
    ),

    # ── Wordlist Generator ─────────────────────────────────────────────────
    Tool(
        id="cupp",
        name="Cupp",
        url="https://github.com/Mebus/cupp",
        category="wordlist",
        description="Common User Passwords Profiler — personalised wordlists.",
        install_cmd="git clone https://github.com/Mebus/cupp",
        run_cmd="python3 cupp/cupp.py {args}",
        flags=["interactive", "long"],
    ),
    Tool(
        id="goblin_wordgen",
        name="Goblin WordGenerator",
        url="https://github.com/UndeadSec/GoblinWordGenerator",
        category="wordlist",
        description="Generates wordlists from website content.",
        install_cmd="git clone https://github.com/UndeadSec/GoblinWordGenerator",
        run_cmd="python3 GoblinWordGenerator/goblin.py {args}",
        reliability="green",
        flags=["long"],
    ),
    Tool(
        id="haiti",
        name="haiti",
        url="https://github.com/noraj/haiti",
        category="wordlist",
        description="Hash type identifier — supports 300+ algorithms.",
        install_cmd="gem install haiti-hash",
        run_cmd="haiti {args}",
        reliability="green",
        flags=["long"],
        aliases=["hash identify", "hash type"],
    ),
    Tool(
        id="hashcat",
        name="Hashcat",
        url="https://github.com/hashcat/hashcat",
        category="wordlist",
        description="World's fastest GPU/CPU password recovery — 300+ hash types.",
        install_cmd="apt-get install -y hashcat",
        run_cmd="hashcat {args}",
        flags=["sudo", "long"],
        aliases=["crack hash", "password crack"],
    ),
    Tool(
        id="john",
        name="John the Ripper",
        url="https://github.com/openwall/john",
        category="wordlist",
        description="Open-source password security auditing.",
        install_cmd="apt-get install -y john",
        run_cmd="john {args}",
        flags=["sudo", "long"],
        aliases=["crack hash", "password crack"],
    ),
    Tool(
        id="smwyg",
        name="Password list (1.4B Clear Text)",
        url="https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got",
        category="wordlist",
        description="Search 1.4 billion clear-text credentials from BreachCompilation.",
        install_cmd="git clone https://github.com/Viralmaniar/SMWYG-Show-Me-What-You-Got",
        run_cmd="python3 SMWYG-Show-Me-What-You-Got/SMWYG.py {args}",
        reliability="green",
        flags=["long"],
    ),
    Tool(
        id="wlcreator",
        name="WordlistCreator",
        url="https://github.com/Z4nzu/wlcreator",
        category="wordlist",
        description="C tool that generates exhaustive password combinations.",
        install_cmd="git clone https://github.com/Z4nzu/wlcreator && cd wlcreator && make",
        run_cmd="./wlcreator/wlcreator {args}",
        flags=["sudo", "long"],
    ),

    # ── Wireless Attack ────────────────────────────────────────────────────
    Tool(
        id="airgeddon",
        name="Airgeddon",
        url="https://github.com/v1s1t0r1sh3r3/airgeddon",
        category="wireless",
        description="Multi-use bash script for wireless network auditing.",
        install_cmd="git clone https://github.com/v1s1t0r1sh3r3/airgeddon",
        run_cmd="sudo bash airgeddon/airgeddon.sh {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="bettercap",
        name="Bettercap",
        url="https://github.com/bettercap/bettercap",
        category="wireless",
        description="Swiss army knife for WiFi, BLE, HID, and Ethernet recon/MITM.",
        install_cmd="apt-get install -y bettercap",
        run_cmd="bettercap {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="bluepot",
        name="Bluetooth Honeypot (bluepot)",
        url="https://github.com/andrewmichaelsmith/bluepot",
        category="wireless",
        description="Bluetooth receiver honeypot.",
        install_cmd="git clone https://github.com/andrewmichaelsmith/bluepot",
        run_cmd="sudo java -jar bluepot/dist/BluePot-0.1.jar {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="eviltwin",
        name="EvilTwin",
        url="https://github.com/Z4nzu/fakeap",
        category="wireless",
        description="Evil twin attack via fake captive portal and access point.",
        install_cmd="git clone https://github.com/Z4nzu/fakeap",
        run_cmd="sudo bash fakeap/eviltwin.sh {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="fastssh",
        name="Fastssh",
        url="https://github.com/Z4nzu/fastssh",
        category="wireless",
        description="Multi-threaded SSH scanner and brute-forcer.",
        install_cmd="git clone https://github.com/Z4nzu/fastssh",
        run_cmd="bash fastssh/fastssh.sh {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="fluxion",
        name="Fluxion",
        url="https://github.com/FluxionNetwork/fluxion",
        category="wireless",
        description="Automated MITM WiFi attack (linset remake).",
        install_cmd="git clone https://github.com/FluxionNetwork/fluxion",
        run_cmd="sudo bash fluxion/fluxion.sh {args}",
        flags=["interactive", "sudo", "hw"],
    ),
    Tool(
        id="hcxdumptool",
        name="hcxdumptool",
        url="https://github.com/ZerBea/hcxdumptool",
        category="wireless",
        description="Capture WLAN packets and PMKID hashes.",
        install_cmd="git clone https://github.com/ZerBea/hcxdumptool && cd hcxdumptool && make && sudo make install",
        run_cmd="hcxdumptool {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="hcxtools",
        name="hcxtools",
        url="https://github.com/ZerBea/hcxtools",
        category="wireless",
        description="Convert WLAN captures to hashcat/JtR format.",
        install_cmd="git clone https://github.com/ZerBea/hcxtools && cd hcxtools && make && sudo make install",
        run_cmd="hcxpcapngtool {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="howmanypeople",
        name="Howmanypeople",
        url="",
        category="wireless",
        description="Count nearby devices by monitoring Wi-Fi probe requests.",
        install_cmd="",
        run_cmd="howmanypeople {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="pixiewps",
        name="pixiewps",
        url="https://github.com/wiire/pixiewps",
        category="wireless",
        description="Offline WPS PIN brute-force (pixie-dust attack).",
        install_cmd="apt-get install -y pixiewps",
        run_cmd="pixiewps {args}",
        flags=["sudo", "hw", "long"],
    ),
    Tool(
        id="wifipumpkin",
        name="WiFi-Pumpkin",
        url="https://github.com/P0cL4bs/wifipumpkin3",
        category="wireless",
        description="Rogue AP framework for creating fake networks.",
        install_cmd="pip3 install wifipumpkin3",
        run_cmd="wifipumpkin3 {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="wifiphisher",
        name="Wifiphisher",
        url="https://github.com/wifiphisher/wifiphisher",
        category="wireless",
        description="Rogue access point framework for red-team ops.",
        install_cmd="git clone https://github.com/wifiphisher/wifiphisher && pip3 install -r wifiphisher/requirements.txt",
        run_cmd="sudo python3 wifiphisher/bin/wifiphisher {args}",
        flags=["sudo", "hw"],
    ),
    Tool(
        id="wifite",
        name="Wifite",
        url="https://github.com/derv82/wifite2",
        category="wireless",
        description="Automated wireless attack tool.",
        install_cmd="git clone https://github.com/derv82/wifite2 && pip3 install -r wifite2/requirements.txt",
        run_cmd="sudo python3 wifite2/Wifite.py {args}",
        flags=["sudo", "hw"],
    ),

    # ── SQL Injection ──────────────────────────────────────────────────────
    Tool(
        id="blisqy",
        name="Blisqy",
        url="https://github.com/JohnTroony/Blisqy",
        category="sqli",
        description="Time-based blind SQLi on HTTP headers.",
        install_cmd="git clone https://github.com/JohnTroony/Blisqy",
        run_cmd="python3 Blisqy/blisqy.py {args}",
    ),
    Tool(
        id="dsss",
        name="DSSS",
        url="https://github.com/stamparm/DSSS",
        category="sqli",
        description="Damn Small SQLi Scanner for GET/POST params.",
        install_cmd="git clone https://github.com/stamparm/DSSS",
        run_cmd="python3 DSSS/dsss.py {args}",
    ),
    Tool(
        id="explo",
        name="Explo",
        url="https://github.com/dtag-dev-sec/explo",
        category="sqli",
        description="Describe web security issues in human/machine-readable format.",
        install_cmd="pip3 install explo",
        run_cmd="explo {args}",
    ),
    Tool(
        id="leviathan",
        name="Leviathan",
        url="https://github.com/leviathan-framework/leviathan",
        category="sqli",
        description="Mass audit toolkit — discovery, brute force, SQLi detection.",
        install_cmd="git clone https://github.com/leviathan-framework/leviathan && pip3 install -r leviathan/requirements.txt",
        run_cmd="python3 leviathan/leviathan.py {args}",
        reliability="green",
    ),
    Tool(
        id="nosqlmap",
        name="NoSqlMap",
        url="https://github.com/codingo/NoSQLMap",
        category="sqli",
        description="Audit and automate NoSQL injection attacks.",
        install_cmd="git clone https://github.com/codingo/NoSQLMap && pip3 install -r NoSQLMap/requirements.txt",
        run_cmd="python3 NoSQLMap/nosqlmap.py {args}",
        reliability="green",
    ),
    Tool(
        id="sqlmap",
        name="sqlmap",
        url="https://github.com/sqlmapproject/sqlmap",
        category="sqli",
        description="Automate detection and exploitation of SQL injection flaws.",
        install_cmd="pip3 install sqlmap",
        run_cmd="sqlmap {args}",
        docker_image="paoloo/sqlmap",
        flags=["interactive"],
        aliases=["sqli", "sql injection"],
    ),
    Tool(
        id="sqlscan",
        name="SQLScan",
        url="https://github.com/Cvar1984/sqlscan",
        category="sqli",
        description="Quick web scanner to find SQL injection points.",
        install_cmd="git clone https://github.com/Cvar1984/sqlscan",
        run_cmd="bash sqlscan/sqlscan.sh {args}",
        flags=["sudo"],
    ),

    # ── Phishing Attack ────────────────────────────────────────────────────
    Tool(
        id="advphishing",
        name="AdvPhishing",
        url="https://github.com/Ignitetch/AdvPhishing",
        category="phishing",
        description="Advanced OTP phishing tool.",
        install_cmd="git clone https://github.com/Ignitetch/AdvPhishing",
        run_cmd="bash AdvPhishing/install.sh && bash AdvPhishing/adv.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="autophisher",
        name="Autophisher",
        url="https://github.com/CodingRanjith/autophisher",
        category="phishing",
        description="Automated phishing toolkit.",
        install_cmd="git clone https://github.com/CodingRanjith/autophisher",
        run_cmd="bash autophisher/autophisher.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="blackeye",
        name="BlackEye",
        url="https://github.com/An0nUD4Y/blackeye",
        category="phishing",
        description="Phishing tool with 38 website templates.",
        install_cmd="git clone https://github.com/An0nUD4Y/blackeye",
        run_cmd="bash blackeye/blackeye.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="blackphish",
        name="BlackPhish",
        url="https://github.com/iinc0gnit0/BlackPhish",
        category="phishing",
        description="Phishing toolkit.",
        install_cmd="git clone https://github.com/iinc0gnit0/BlackPhish",
        run_cmd="bash BlackPhish/BlackPhish.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="dnstwist",
        name="dnstwist",
        url="https://github.com/elceef/dnstwist",
        category="phishing",
        description="Domain permutation engine — typosquatting and brand impersonation.",
        install_cmd="pip3 install dnstwist",
        run_cmd="dnstwist {args}",
        docker_image="elceef/dnstwist",
        reliability="green",
        aliases=["typosquat", "phishing recon"],
    ),
    Tool(
        id="evilginx3",
        name="Evilginx3",
        url="https://github.com/kgretzky/evilginx2",
        category="phishing",
        description="MITM attack framework for phishing credentials.",
        install_cmd="git clone https://github.com/kgretzky/evilginx2 && cd evilginx2 && make",
        run_cmd="sudo ./evilginx2/bin/evilginx {args}",
        flags=["sudo"],
    ),
    Tool(
        id="hiddeneye",
        name="HiddenEye",
        url="https://github.com/Morsmalleo/HiddenEye",
        category="phishing",
        description="Modern phishing tool with multi-tunnelling.",
        install_cmd="git clone https://github.com/Morsmalleo/HiddenEye && pip3 install -r HiddenEye/requirements.txt",
        run_cmd="python3 HiddenEye/HiddenEye.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="i_see_you",
        name="I-See-You",
        url="https://github.com/Viralmaniar/I-See-You",
        category="phishing",
        description="Geolocation capture via social engineering.",
        install_cmd="git clone https://github.com/Viralmaniar/I-See-You",
        run_cmd="python3 I-See-You/ISeeYou.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="maskphish",
        name="Maskphish",
        url="https://github.com/jaykali/maskphish",
        category="phishing",
        description="Mask phishing URLs behind legitimate-looking links.",
        install_cmd="git clone https://github.com/jaykali/maskphish",
        run_cmd="bash maskphish/maskphish.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="pyphisher",
        name="PyPhisher",
        url="https://github.com/KasRoudra/PyPhisher",
        category="phishing",
        description="Easy phishing tool with 77 website templates.",
        install_cmd="git clone https://github.com/KasRoudra/PyPhisher && pip3 install -r PyPhisher/requirements.txt",
        run_cmd="python3 PyPhisher/pyphisher.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="qr_jacking",
        name="QR Code Jacking",
        url="https://github.com/cryptedwolf/ohmyqr",
        category="phishing",
        description="QR Code Jacking for any website.",
        install_cmd="git clone https://github.com/cryptedwolf/ohmyqr",
        run_cmd="bash ohmyqr/install.sh && bash ohmyqr/run.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="qrljacking",
        name="QRLJacking",
        url="https://github.com/OWASP/QRLJacking",
        category="phishing",
        description="Session hijacking against QR-code-based login.",
        install_cmd="git clone https://github.com/OWASP/QRLJacking",
        run_cmd="python3 QRLJacking/QRLJacking.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="saycheese",
        name="SayCheese",
        url="https://github.com/hangetzzu/saycheese",
        category="phishing",
        description="Grab webcam shots from target via malicious link.",
        install_cmd="git clone https://github.com/hangetzzu/saycheese",
        run_cmd="bash saycheese/saycheese.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="setoolkit",
        name="SEToolkit",
        url="https://github.com/trustedsec/social-engineer-toolkit",
        category="phishing",
        description="The Social-Engineer Toolkit.",
        install_cmd="git clone https://github.com/trustedsec/social-engineer-toolkit && pip3 install -r social-engineer-toolkit/requirements.txt",
        run_cmd="sudo python3 social-engineer-toolkit/se-toolkit {args}",
        flags=["sudo"],
    ),
    Tool(
        id="shellphish",
        name="ShellPhish",
        url="https://github.com/An0nUD4Y/shellphish",
        category="phishing",
        description="Phishing pages for 18 social media platforms.",
        install_cmd="git clone https://github.com/An0nUD4Y/shellphish",
        run_cmd="bash shellphish/shellphish.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="socialfish",
        name="SocialFish",
        url="https://github.com/UndeadSec/SocialFish",
        category="phishing",
        description="Automated phishing tool with information gathering.",
        install_cmd="git clone https://github.com/UndeadSec/SocialFish && pip3 install -r SocialFish/requirements.txt",
        run_cmd="python3 SocialFish/SocialFish.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="thanos",
        name="Thanos",
        url="https://github.com/TridevReddy/Thanos",
        category="phishing",
        description="Browser-to-browser phishing toolkit.",
        install_cmd="git clone https://github.com/TridevReddy/Thanos",
        run_cmd="bash Thanos/thanos.sh {args}",
        flags=["sudo"],
    ),

    # ── Web Attack ─────────────────────────────────────────────────────────
    Tool(
        id="arjun",
        name="Arjun",
        url="https://github.com/s0md3v/Arjun",
        category="web",
        description="HTTP parameter discovery — hidden GET/POST params.",
        install_cmd="pip3 install arjun",
        run_cmd="arjun {args}",
        reliability="green",
        aliases=["parameter discovery"],
    ),
    Tool(
        id="blazy",
        name="Blazy",
        url="https://github.com/UltimateHackers/Blazy",
        category="web",
        description="Login page brute-forcer (also clickjacking checks).",
        install_cmd="git clone https://github.com/UltimateHackers/Blazy && pip3 install -r Blazy/requirements.txt",
        run_cmd="python3 Blazy/blazy.py {args}",
        flags=["archived"],
    ),
    Tool(
        id="caido",
        name="Caido",
        url="https://github.com/caido/caido",
        category="web",
        description="Lightweight web security auditing toolkit — Burp alternative.",
        install_cmd="curl -sSL https://caido.io/install.sh | bash",
        run_cmd="caido {args}",
        flags=["sudo"],
    ),
    Tool(
        id="checkurl",
        name="CheckURL",
        url="https://github.com/UndeadSec/checkURL",
        category="web",
        description="Detect evil URLs using IDN Homograph Attack.",
        install_cmd="git clone https://github.com/UndeadSec/checkURL",
        run_cmd="python3 checkURL/checkURL.py {args}",
        reliability="green",
    ),
    Tool(
        id="dirb",
        name="Dirb",
        url="https://gitlab.com/kalilinux/packages/dirb",
        category="web",
        description="Web content scanner for existing and hidden objects.",
        install_cmd="apt-get install -y dirb",
        run_cmd="dirb {args}",
        flags=["interactive", "sudo"],
    ),
    Tool(
        id="dirsearch",
        name="Dirsearch",
        url="https://github.com/maurosoria/dirsearch",
        category="web",
        description="Web path brute-forcing tool.",
        install_cmd="pip3 install dirsearch",
        run_cmd="dirsearch {args}",
        reliability="green",
        aliases=["directory brute force"],
    ),
    Tool(
        id="feroxbuster",
        name="Feroxbuster",
        url="https://github.com/epi052/feroxbuster",
        category="web",
        description="Fast, recursive content discovery in Rust.",
        install_cmd="cargo install feroxbuster",
        run_cmd="feroxbuster {args}",
        flags=["sudo", "long"],
    ),
    Tool(
        id="ffuf",
        name="ffuf",
        url="https://github.com/ffuf/ffuf",
        category="web",
        description="Fast web fuzzer — content, parameter, vhost discovery.",
        install_cmd="go install github.com/ffuf/ffuf/v2@latest",
        run_cmd="ffuf {args}",
        docker_image="secsi/ffuf",
        reliability="green",
        flags=["long"],
        aliases=["fuzz", "directory fuzz"],
    ),
    Tool(
        id="gobuster",
        name="Gobuster",
        url="https://github.com/OJ/gobuster",
        category="web",
        description="Directory/file, DNS, and vhost brute-forcing in Go.",
        install_cmd="go install github.com/OJ/gobuster/v3@latest",
        run_cmd="gobuster {args}",
        docker_image="devopsworks/gobuster",
        reliability="green",
        aliases=["directory brute force"],
    ),
    Tool(
        id="katana",
        name="Katana",
        url="https://github.com/projectdiscovery/katana",
        category="web",
        description="Next-generation crawling and spidering framework.",
        install_cmd="go install github.com/projectdiscovery/katana/cmd/katana@latest",
        run_cmd="katana {args}",
        docker_image="projectdiscovery/katana",
        reliability="green",
        aliases=["web crawl", "spider"],
    ),
    Tool(
        id="mitmproxy",
        name="mitmproxy",
        url="https://github.com/mitmproxy/mitmproxy",
        category="web",
        description="TLS-capable intercepting HTTP proxy.",
        install_cmd="pip3 install mitmproxy",
        run_cmd="mitmproxy {args}",
        reliability="green",
    ),
    Tool(
        id="nikto",
        name="Nikto",
        url="https://github.com/sullo/nikto",
        category="web",
        description="Scan web servers for dangerous files, outdated software, misconfiguration.",
        install_cmd="apt-get install -y nikto",
        run_cmd="nikto {args}",
        flags=["sudo"],
        aliases=["web server scan"],
    ),
    Tool(
        id="nuclei",
        name="Nuclei",
        url="https://github.com/projectdiscovery/nuclei",
        category="web",
        description="Fast template-based vulnerability scanner.",
        install_cmd="go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
        run_cmd="nuclei {args}",
        docker_image="projectdiscovery/nuclei",
        reliability="green",
        aliases=["vuln scan", "vulnerability scanner"],
    ),
    Tool(
        id="owasp_zap",
        name="OWASP ZAP",
        url="https://github.com/zaproxy/zaproxy",
        category="web",
        description="Full-featured web application security scanner.",
        install_cmd="apt-get install -y zaproxy",
        run_cmd="zap.sh {args}",
        flags=["sudo", "gui"],
    ),
    Tool(
        id="skipfish",
        name="Skipfish",
        url="https://code.google.com/archive/p/skipfish/",
        category="web",
        description="Automated active web application security recon.",
        install_cmd="apt-get install -y skipfish",
        run_cmd="skipfish {args}",
        flags=["sudo"],
    ),
    Tool(
        id="subdomain_takeover",
        name="Sub-Domain TakeOver",
        url="https://github.com/edoardottt/takeover",
        category="web",
        description="Sub-domain takeover scanner.",
        install_cmd="go install github.com/edoardottt/takeover@latest",
        run_cmd="takeover {args}",
    ),
    Tool(
        id="sublist3r",
        name="Sublist3r",
        url="https://github.com/aboul3la/Sublist3r",
        category="web",
        description="Enumerate subdomains using OSINT.",
        install_cmd="pip3 install sublist3r",
        run_cmd="sublist3r {args}",
        flags=["sudo"],
    ),
    Tool(
        id="testssl",
        name="testssl.sh",
        url="https://github.com/drwetter/testssl.sh",
        category="web",
        description="Check TLS/SSL ciphers, protocols, and cryptographic flaws.",
        install_cmd="git clone https://github.com/drwetter/testssl.sh",
        run_cmd="bash testssl.sh/testssl.sh {args}",
        docker_image="drwetter/testssl.sh",
        reliability="green",
        aliases=["ssl check", "tls check"],
    ),
    Tool(
        id="wafw00f",
        name="wafw00f",
        url="https://github.com/EnableSecurity/wafw00f",
        category="web",
        description="Fingerprint and identify Web Application Firewalls.",
        install_cmd="pip3 install wafw00f",
        run_cmd="wafw00f {args}",
        docker_image="0xsauby/wafw00f",
        reliability="green",
        aliases=["waf detect", "waf fingerprint"],
    ),
    Tool(
        id="web2attack",
        name="Web2Attack",
        url="https://github.com/santatic/web2attack",
        category="web",
        description="Web hacking framework with tools and exploits.",
        install_cmd="git clone https://github.com/santatic/web2attack",
        run_cmd="python3 web2attack/w2a.py {args}",
        flags=["sudo"],
    ),

    # ── Post Exploitation ──────────────────────────────────────────────────
    Tool(
        id="chisel",
        name="Chisel",
        url="https://github.com/jpillora/chisel",
        category="postex",
        description="Fast TCP/UDP tunnel over HTTP — pivoting and port forwarding.",
        install_cmd="go install github.com/jpillora/chisel@latest",
        run_cmd="chisel {args}",
        reliability="green",
        aliases=["tunnel", "pivot"],
    ),
    Tool(
        id="chrome_keylogger",
        name="Chrome Keylogger",
        url="https://github.com/UndeadSec/HeraKeylogger",
        category="postex",
        description="Hera Chrome extension keylogger.",
        install_cmd="git clone https://github.com/UndeadSec/HeraKeylogger",
        run_cmd="python3 HeraKeylogger/hera.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="evil_winrm",
        name="Evil-WinRM",
        url="https://github.com/Hackplayers/evil-winrm",
        category="postex",
        description="Ultimate WinRM shell for Windows pentesting.",
        install_cmd="gem install evil-winrm",
        run_cmd="evil-winrm {args}",
        reliability="green",
        aliases=["winrm", "windows shell"],
    ),
    Tool(
        id="havoc",
        name="Havoc",
        url="https://github.com/HavocFramework/Havoc",
        category="postex",
        description="Modern post-exploitation C2 with EDR evasion.",
        install_cmd="git clone https://github.com/HavocFramework/Havoc",
        run_cmd="./Havoc/havoc {args}",
        reliability="green",
        aliases=["c2", "command and control"],
    ),
    Tool(
        id="ligolo_ng",
        name="Ligolo-ng",
        url="https://github.com/nicocha30/ligolo-ng",
        category="postex",
        description="Advanced tunneling/pivoting via TUN interfaces.",
        install_cmd="go install github.com/nicocha30/ligolo-ng/cmd/proxy@latest",
        run_cmd="proxy {args}",
        reliability="green",
        aliases=["tunnel", "pivot"],
    ),
    Tool(
        id="mythic",
        name="Mythic",
        url="https://github.com/its-a-feature/Mythic",
        category="postex",
        description="Collaborative multi-payload C2 platform for red team ops.",
        install_cmd="git clone https://github.com/its-a-feature/Mythic && cd Mythic && make",
        run_cmd="./Mythic/mythic-cli {args}",
        flags=["sudo"],
        aliases=["c2"],
    ),
    Tool(
        id="peass",
        name="PEASS-ng (LinPEAS/WinPEAS)",
        url="https://github.com/peass-ng/PEASS-ng",
        category="postex",
        description="Privilege escalation enumeration for Linux and Windows.",
        install_cmd="curl -sSL https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh -o linpeas.sh",
        run_cmd="bash linpeas.sh {args}",
        reliability="green",
        aliases=["privesc", "privilege escalation"],
    ),
    Tool(
        id="pwncat",
        name="pwncat-cs",
        url="https://github.com/calebstewart/pwncat",
        category="postex",
        description="Post-exploitation platform — manages reverse/bind shells.",
        install_cmd="pip3 install pwncat-cs",
        run_cmd="pwncat-cs {args}",
        reliability="green",
    ),
    Tool(
        id="sliver",
        name="Sliver",
        url="https://github.com/BishopFox/sliver",
        category="postex",
        description="Cross-platform adversary emulation / red team C2.",
        install_cmd="curl -sSL https://sliver.sh/install | sudo bash",
        run_cmd="sliver {args}",
        flags=["sudo"],
        aliases=["c2"],
    ),
    Tool(
        id="vegile",
        name="Vegile",
        url="https://github.com/Screetsec/Vegile",
        category="postex",
        description="Backdoor/rootkit setup after initial compromise.",
        install_cmd="git clone https://github.com/Screetsec/Vegile",
        run_cmd="bash Vegile/Vegile.sh {args}",
        flags=["sudo"],
    ),

    # ── Forensics (original 8) ─────────────────────────────────────────────
    Tool(
        id="autopsy",
        name="Autopsy",
        url="https://www.autopsy.com/",
        category="forensics",
        description="GUI forensic investigation platform.",
        install_cmd="apt-get install -y autopsy",
        run_cmd="autopsy {args}",
        flags=["sudo", "gui"],
        aliases=["forensic", "disk image analysis"],
    ),
    Tool(
        id="binwalk",
        name="Binwalk",
        url="https://github.com/ReFirmLabs/binwalk",
        category="forensics",
        description="Analyze, reverse-engineer, and extract firmware images.",
        install_cmd="pip3 install binwalk",
        run_cmd="binwalk {args}",
        reliability="green",
        aliases=["firmware analysis", "embedded analysis"],
    ),
    Tool(
        id="bulk_extractor",
        name="Bulk Extractor",
        url="https://github.com/simsong/bulk_extractor",
        category="forensics",
        description="Extract useful information without parsing the filesystem.",
        install_cmd="apt-get install -y bulk-extractor",
        run_cmd="bulk_extractor {args}",
        aliases=["artifact extraction"],
    ),
    Tool(
        id="guymager",
        name="Guymager",
        url="https://guymager.sourceforge.io/",
        category="forensics",
        description="Free forensic imager for media acquisition.",
        install_cmd="apt-get install -y guymager",
        run_cmd="guymager {args}",
        flags=["sudo"],
        aliases=["disk image", "forensic image"],
    ),
    Tool(
        id="pspy",
        name="pspy",
        url="https://github.com/DominicBreuker/pspy",
        category="forensics",
        description="Monitor Linux processes without root — catches cron/scheduled tasks.",
        install_cmd="curl -sSL https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64 -o pspy && chmod +x pspy",
        run_cmd="./pspy {args}",
        reliability="green",
        aliases=["process monitor", "cron monitor"],
    ),
    Tool(
        id="toolsley",
        name="Toolsley",
        url="https://www.toolsley.com/",
        category="forensics",
        description="10+ online tools for file investigation.",
        install_cmd="",
        run_cmd="# open https://www.toolsley.com/ in browser",
    ),
    Tool(
        id="volatility3",
        name="Volatility 3",
        url="https://github.com/volatilityfoundation/volatility3",
        category="forensics",
        description="World's most widely used memory forensics framework.",
        install_cmd="pip3 install volatility3",
        run_cmd="vol {args}",
        flags=["interactive"],
        aliases=["memory forensics", "memory analysis", "ram forensics"],
    ),
    Tool(
        id="wireshark",
        name="Wireshark",
        url="https://www.wireshark.org/",
        category="forensics",
        description="Network packet capture and deep protocol analyzer.",
        install_cmd="apt-get install -y wireshark",
        run_cmd="wireshark {args}",
        flags=["sudo", "gui"],
        aliases=["packet capture", "pcap analysis"],
    ),

    # ── Payload Creation ───────────────────────────────────────────────────
    Tool(
        id="brutal",
        name="Brutal",
        url="https://github.com/Screetsec/Brutal",
        category="payload",
        description="Payload toolkit — PowerShell, HID, and more.",
        install_cmd="git clone https://github.com/Screetsec/Brutal",
        run_cmd="bash Brutal/brutal.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="enigma",
        name="Enigma",
        url="https://github.com/UndeadSec/Enigma",
        category="payload",
        description="Multiplatform payload dropper.",
        install_cmd="git clone https://github.com/UndeadSec/Enigma",
        run_cmd="python3 Enigma/enigma.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="mob_droid",
        name="Mob-Droid",
        url="https://github.com/kinghacker0/Mob-Droid",
        category="payload",
        description="Generate Metasploit payloads for Android.",
        install_cmd="git clone https://github.com/kinghacker0/Mob-Droid",
        run_cmd="bash Mob-Droid/mob-droid.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="msfpc",
        name="MSFvenom Payload Creator",
        url="https://github.com/g0tmi1k/msfpc",
        category="payload",
        description="Wrapper to generate MSFvenom payloads quickly.",
        install_cmd="git clone https://github.com/g0tmi1k/msfpc",
        run_cmd="bash msfpc/msfpc.sh {args}",
        flags=["sudo"],
    ),
    Tool(
        id="spycam",
        name="Spycam",
        url="https://github.com/indexnotfound404/spycam",
        category="payload",
        description="Webcam capture payload.",
        install_cmd="git clone https://github.com/indexnotfound404/spycam",
        run_cmd="python3 spycam/spycam.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="stitch",
        name="Stitch",
        url="https://nathanlopez.github.io/Stitch",
        category="payload",
        description="Python remote administration tool framework.",
        install_cmd="pip3 install stitch-framework",
        run_cmd="stitch {args}",
        flags=["sudo"],
    ),
    Tool(
        id="thefatrat",
        name="The FatRat",
        url="https://github.com/Screetsec/TheFatRat",
        category="payload",
        description="Easy payload generator with backdoor capabilities.",
        install_cmd="git clone https://github.com/Screetsec/TheFatRat && bash TheFatRat/setup.sh",
        run_cmd="bash TheFatRat/fatrat {args}",
        flags=["sudo"],
    ),
    Tool(
        id="venom",
        name="Venom",
        url="https://github.com/r00t-3xp10it/venom",
        category="payload",
        description="Metasploit shellcode generator and listener.",
        install_cmd="git clone https://github.com/r00t-3xp10it/venom",
        run_cmd="bash venom/venom.sh {args}",
        flags=["sudo"],
    ),

    # ── Exploit Framework ──────────────────────────────────────────────────
    Tool(
        id="commix",
        name="Commix",
        url="https://github.com/commixproject/commix",
        category="exploit",
        description="Automated command injection and exploitation tool.",
        install_cmd="pip3 install commix",
        run_cmd="commix {args}",
        aliases=["command injection"],
    ),
    Tool(
        id="routersploit",
        name="RouterSploit",
        url="https://github.com/threat9/routersploit",
        category="exploit",
        description="Exploitation framework for embedded devices.",
        install_cmd="pip3 install routersploit",
        run_cmd="rsf {args}",
        aliases=["router exploit"],
    ),
    Tool(
        id="web2attack_exploit",
        name="Web2Attack (Exploit)",
        url="https://github.com/santatic/web2attack",
        category="exploit",
        description="Web hacking framework with exploits.",
        install_cmd="git clone https://github.com/santatic/web2attack",
        run_cmd="python3 web2attack/w2a.py {args}",
        flags=["sudo"],
    ),
    Tool(
        id="websploit",
        name="WebSploit",
        url="https://github.com/The404Hacking/websploit",
        category="exploit",
        description="Advanced MITM framework and web network exploitation.",
        install_cmd="git clone https://github.com/The404Hacking/websploit",
        run_cmd="python3 websploit/websploit.py {args}",
    ),

    # ── Reverse Engineering ────────────────────────────────────────────────
    Tool(
        id="androguard",
        name="Androguard",
        url="https://github.com/androguard/androguard",
        category="reveng",
        description="Reverse engineering and analysis of Android applications.",
        install_cmd="pip3 install androguard",
        run_cmd="androguard {args}",
        aliases=["android reverse"],
    ),
    Tool(
        id="apk2gold",
        name="Apk2Gold",
        url="https://github.com/lxdvs/apk2gold",
        category="reveng",
        description="Decompile Android applications to Java.",
        install_cmd="git clone https://github.com/lxdvs/apk2gold",
        run_cmd="python3 apk2gold/apk2gold.py {args}",
        aliases=["android decompile"],
    ),
    Tool(
        id="ghidra",
        name="Ghidra",
        url="https://github.com/NationalSecurityAgency/ghidra",
        category="reveng",
        description="NSA's free and open-source reverse engineering tool.",
        install_cmd="apt-get install -y ghidra",
        run_cmd="ghidra {args}",
        reliability="green",
        flags=["gui"],
        aliases=["disassemble", "decompile", "binary analysis"],
    ),
    Tool(
        id="jadx",
        name="JadX",
        url="https://github.com/skylot/jadx",
        category="reveng",
        description="Dex to Java decompiler.",
        install_cmd="apt-get install -y jadx",
        run_cmd="jadx {args}",
        aliases=["android decompile", "dex decompile"],
    ),
    Tool(
        id="radare2",
        name="Radare2",
        url="https://github.com/radareorg/radare2",
        category="reveng",
        description="Portable reversing framework for binary analysis.",
        install_cmd="apt-get install -y radare2",
        run_cmd="r2 {args}",
        reliability="green",
        aliases=["binary analysis", "disassemble"],
    ),

    # ── DDoS Attack ────────────────────────────────────────────────────────
    Tool(
        id="asyncrone",
        name="Asyncrone",
        url="https://github.com/fatihsnsy/aSYNcrone",
        category="ddos",
        description="Multifunctional SYN Flood DDoS tool.",
        install_cmd="git clone https://github.com/fatihsnsy/aSYNcrone",
        run_cmd="./aSYNcrone/asyncrone {args}",
    ),
    Tool(
        id="ddos_script",
        name="DDoS Script",
        url="https://github.com/the-deepnet/ddos",
        category="ddos",
        description="Python DDoS attack scripts.",
        install_cmd="git clone https://github.com/the-deepnet/ddos",
        run_cmd="python3 ddos/ddos.py {args}",
    ),
    Tool(
        id="goldeneye",
        name="GoldenEye",
        url="https://github.com/jseidl/GoldenEye",
        category="ddos",
        description="HTTP DDoS test tool.",
        install_cmd="git clone https://github.com/jseidl/GoldenEye",
        run_cmd="python3 GoldenEye/goldeneye.py {args}",
    ),
    Tool(
        id="slowloris",
        name="SlowLoris",
        url="https://github.com/gkbrk/slowloris",
        category="ddos",
        description="Low-bandwidth denial-of-service attack tool.",
        install_cmd="pip3 install slowloris",
        run_cmd="slowloris {args}",
    ),
    Tool(
        id="ufonet",
        name="UFOnet",
        url="https://github.com/epsylon/ufonet",
        category="ddos",
        description="Distributed cyber attack tool using Open Redirect vectors.",
        install_cmd="git clone https://github.com/epsylon/ufonet && pip3 install -r ufonet/requirements.txt",
        run_cmd="python3 ufonet/ufonet.py {args}",
    ),

    # ── RAT ────────────────────────────────────────────────────────────────
    Tool(
        id="pyshell",
        name="Pyshell",
        url="https://github.com/knassar702/pyshell",
        category="rat",
        description="Multi-platform RAT written in Python.",
        install_cmd="git clone https://github.com/knassar702/pyshell && pip3 install -r pyshell/requirements.txt",
        run_cmd="python3 pyshell/pyshell.py {args}",
    ),

    # ── XSS Attack ─────────────────────────────────────────────────────────
    Tool(
        id="dalfox",
        name="DalFox",
        url="https://github.com/hahwul/dalfox",
        category="xss",
        description="Powerful XSS scanning and parameter analysis tool.",
        install_cmd="go install github.com/hahwul/dalfox/v2@latest",
        run_cmd="dalfox {args}",
        reliability="green",
        aliases=["xss scan"],
    ),
    Tool(
        id="extended_xss_searcher",
        name="Extended XSS Searcher",
        url="https://github.com/Damian89/extended-xss-search",
        category="xss",
        description="Automated XSS scanner with multiple payloads.",
        install_cmd="git clone https://github.com/Damian89/extended-xss-search && pip3 install -r extended-xss-search/requirements.txt",
        run_cmd="python3 extended-xss-search/xss-search.py {args}",
    ),
    Tool(
        id="rvuln",
        name="RVuln",
        url="https://github.com/iinc0gnit0/RVuln",
        category="xss",
        description="Fast web vulnerability scanner.",
        install_cmd="git clone https://github.com/iinc0gnit0/RVuln",
        run_cmd="bash RVuln/rvuln.sh {args}",
    ),
    Tool(
        id="xanxss",
        name="XanXSS",
        url="https://github.com/Ekultek/XanXSS",
        category="xss",
        description="Advanced XSS detection and exploitation.",
        install_cmd="git clone https://github.com/Ekultek/XanXSS && pip3 install -r XanXSS/requirements.txt",
        run_cmd="python3 XanXSS/xanxss.py {args}",
    ),
    Tool(
        id="xspear",
        name="XSpear",
        url="https://github.com/hahwul/XSpear",
        category="xss",
        description="Powerful XSS scanning and parameter analysis.",
        install_cmd="gem install XSpear",
        run_cmd="XSpear {args}",
    ),
    Tool(
        id="xss_freak",
        name="XSS-Freak",
        url="https://github.com/PR0PH3CY33/XSS-Freak",
        category="xss",
        description="XSS crawler and scanner.",
        install_cmd="git clone https://github.com/PR0PH3CY33/XSS-Freak && pip3 install -r XSS-Freak/requirements.txt",
        run_cmd="python3 XSS-Freak/xssfreak.py {args}",
    ),
    Tool(
        id="xss_loader",
        name="XSS Payload Generator",
        url="https://github.com/capture0x/XSS-LOADER",
        category="xss",
        description="XSS payload loader and encoder.",
        install_cmd="git clone https://github.com/capture0x/XSS-LOADER",
        run_cmd="python3 XSS-LOADER/xssloader.py {args}",
    ),
    Tool(
        id="xsscon",
        name="XSSCon",
        url="https://github.com/menkrep1337/XSSCon",
        category="xss",
        description="Powerful XSS scanner.",
        install_cmd="git clone https://github.com/menkrep1337/XSSCon && pip3 install -r XSSCon/requirements.txt",
        run_cmd="python3 XSSCon/xsscon.py {args}",
    ),
    Tool(
        id="xsstrike",
        name="XSStrike",
        url="https://github.com/UltimateHackers/XSStrike",
        category="xss",
        description="Advanced XSS detection suite.",
        install_cmd="git clone https://github.com/UltimateHackers/XSStrike && pip3 install -r XSStrike/requirements.txt",
        run_cmd="python3 XSStrike/xsstrike.py {args}",
    ),

    # ── Steganography ──────────────────────────────────────────────────────
    Tool(
        id="snow",
        name="Whitespace Steganography (snow)",
        url="https://github.com/beardog108/snow10",
        category="stego",
        description="Conceal messages in whitespace of text files.",
        install_cmd="apt-get install -y steghide",
        run_cmd="snow {args}",
    ),
    Tool(
        id="steghide",
        name="SteganoHide",
        url="https://steghide.sourceforge.net/",
        category="stego",
        description="Hide data in JPEG, BMP, WAV and AU files.",
        install_cmd="apt-get install -y steghide",
        run_cmd="steghide {args}",
        aliases=["steganography", "hide data"],
    ),
    Tool(
        id="stegocracker",
        name="StegoCracker",
        url="https://github.com/W1LDN16H7/StegoCracker",
        category="stego",
        description="Brute-force steghide passwords.",
        install_cmd="git clone https://github.com/W1LDN16H7/StegoCracker",
        run_cmd="python3 StegoCracker/stego-cracker.py {args}",
        aliases=["crack steganography"],
    ),

    # ── Active Directory ───────────────────────────────────────────────────
    Tool(
        id="bloodhound",
        name="BloodHound",
        url="https://github.com/BloodHoundAD/BloodHound",
        category="ad",
        description="Attack path mapping in Active Directory / Azure.",
        install_cmd="apt-get install -y bloodhound",
        run_cmd="bloodhound {args}",
        reliability="green",
        aliases=["active directory", "ad attack path"],
    ),
    Tool(
        id="certipy",
        name="Certipy",
        url="https://github.com/ly4k/Certipy",
        category="ad",
        description="Active Directory Certificate Services enumeration and abuse.",
        install_cmd="pip3 install certipy-ad",
        run_cmd="certipy {args}",
        reliability="green",
        aliases=["adcs", "certificate abuse"],
    ),
    Tool(
        id="impacket",
        name="Impacket",
        url="https://github.com/fortra/impacket",
        category="ad",
        description="Python classes for working with network protocols.",
        install_cmd="pip3 install impacket",
        run_cmd="impacket-{args}",
        docker_image="rflathers/impacket",
        reliability="green",
        aliases=["kerberos", "smb", "pass the hash"],
    ),
    Tool(
        id="kerbrute",
        name="Kerbrute",
        url="https://github.com/ropnop/kerbrute",
        category="ad",
        description="Enumerate and brute-force AD accounts via Kerberos pre-auth.",
        install_cmd="go install github.com/ropnop/kerbrute@latest",
        run_cmd="kerbrute {args}",
        reliability="green",
        aliases=["kerberos enum", "as-rep roasting"],
    ),
    Tool(
        id="netexec",
        name="NetExec (nxc)",
        url="https://github.com/Pennyw0rth/NetExec",
        category="ad",
        description="Network exploitation and post-exploitation tool (CrackMapExec successor).",
        install_cmd="pip3 install netexec",
        run_cmd="nxc {args}",
        docker_image="byt3bl33d3r/netexec",
        reliability="green",
        aliases=["cme", "crackmapexec", "lateral movement"],
    ),
    Tool(
        id="responder",
        name="Responder",
        url="https://github.com/lgandx/Responder",
        category="ad",
        description="LLMNR/NBNS/mDNS poisoner for credential capture.",
        install_cmd="git clone https://github.com/lgandx/Responder",
        run_cmd="sudo python3 Responder/Responder.py {args}",
        reliability="green",
        flags=["sudo"],
        aliases=["credential capture", "llmnr poison"],
    ),

    # ── Cloud Security ─────────────────────────────────────────────────────
    Tool(
        id="pacu",
        name="Pacu",
        url="https://github.com/RhinoSecurityLabs/pacu",
        category="cloud",
        description="AWS exploitation framework.",
        install_cmd="pip3 install pacu",
        run_cmd="pacu {args}",
        reliability="green",
        aliases=["aws attack", "aws pentest"],
    ),
    Tool(
        id="prowler",
        name="Prowler",
        url="https://github.com/prowler-cloud/prowler",
        category="cloud",
        description="AWS/Azure/GCP security assessment tool.",
        install_cmd="pip3 install prowler",
        run_cmd="prowler {args}",
        reliability="green",
        aliases=["cloud audit", "cloud security"],
    ),
    Tool(
        id="scoutsuite",
        name="ScoutSuite",
        url="https://github.com/nccgroup/ScoutSuite",
        category="cloud",
        description="Multi-cloud security auditing tool.",
        install_cmd="pip3 install scoutsuite",
        run_cmd="scout {args}",
        reliability="green",
        aliases=["cloud audit"],
    ),
    Tool(
        id="trivy",
        name="Trivy",
        url="https://github.com/aquasecurity/trivy",
        category="cloud",
        description="Comprehensive container/IaC vulnerability scanner.",
        install_cmd="apt-get install -y trivy",
        run_cmd="trivy {args}",
        reliability="green",
        aliases=["container scan", "docker scan", "iac scan"],
    ),

    # ── Mobile Security ────────────────────────────────────────────────────
    Tool(
        id="frida",
        name="Frida",
        url="https://github.com/frida/frida",
        category="mobile",
        description="Dynamic instrumentation toolkit for iOS and Android.",
        install_cmd="pip3 install frida-tools",
        run_cmd="frida {args}",
        reliability="green",
        aliases=["dynamic analysis", "hooking"],
    ),
    Tool(
        id="mobsf",
        name="MobSF",
        url="https://github.com/MobSF/Mobile-Security-Framework-MobSF",
        category="mobile",
        description="Mobile app security testing framework (iOS/Android/Windows).",
        install_cmd="pip3 install mobsf",
        run_cmd="mobsf {args}",
        flags=["sudo"],
        aliases=["apk analysis", "mobile pentest"],
    ),
    Tool(
        id="objection",
        name="Objection",
        url="https://github.com/sensepost/objection",
        category="mobile",
        description="Runtime mobile exploration powered by Frida.",
        install_cmd="pip3 install objection",
        run_cmd="objection {args}",
        reliability="green",
        aliases=["runtime analysis", "mobile bypass"],
    ),

    # ── Other Tools ────────────────────────────────────────────────────────
    Tool(
        id="allinone_brute",
        name="AllinOne SocialMedia Attack",
        url="https://github.com/Matrix07ksa/Brute_Force",
        category="other",
        description="Brute-force multiple social media platforms.",
        install_cmd="git clone https://github.com/Matrix07ksa/Brute_Force",
        run_cmd="python3 Brute_Force/brute.py {args}",
    ),
    Tool(
        id="crivo",
        name="Crivo",
        url="https://github.com/GMDSantana/crivo",
        category="other",
        description="Filter and process text data.",
        install_cmd="git clone https://github.com/GMDSantana/crivo",
        run_cmd="python3 crivo/crivo.py {args}",
        reliability="green",
    ),
    Tool(
        id="debinject",
        name="Debinject",
        url="https://github.com/UndeadSec/Debinject",
        category="other",
        description="Inject payloads into .deb packages.",
        install_cmd="git clone https://github.com/UndeadSec/Debinject",
        run_cmd="bash Debinject/debinject.sh {args}",
    ),
    Tool(
        id="evilurl",
        name="EvilURL",
        url="https://github.com/UndeadSec/EvilURL",
        category="other",
        description="Generate IDN Homograph Attack URLs.",
        install_cmd="git clone https://github.com/UndeadSec/EvilURL",
        run_cmd="python3 EvilURL/evilurl.py {args}",
    ),
    Tool(
        id="gospider",
        name="Gospider",
        url="https://github.com/jaeles-project/gospider",
        category="other",
        description="Fast web spider written in Go.",
        install_cmd="go install github.com/jaeles-project/gospider@latest",
        run_cmd="gospider {args}",
        reliability="green",
        aliases=["web crawl", "spider"],
    ),
    Tool(
        id="hash_buster",
        name="Hash Buster",
        url="https://github.com/s0md3v/Hash-Buster",
        category="other",
        description="Crack hashes online automatically.",
        install_cmd="pip3 install hash-buster",
        run_cmd="hash-buster {args}",
    ),
    Tool(
        id="keydroid",
        name="Keydroid",
        url="https://github.com/F4dl0/keydroid",
        category="other",
        description="Android keylogger.",
        install_cmd="git clone https://github.com/F4dl0/keydroid",
        run_cmd="bash keydroid/keydroid.sh {args}",
    ),
    Tool(
        id="knockmail",
        name="Knockmail",
        url="https://github.com/4w4k3/KnockMail",
        category="other",
        description="Verify if an email address exists.",
        install_cmd="pip3 install knockmail",
        run_cmd="knockmail {args}",
    ),
    Tool(
        id="pixload",
        name="Pixload",
        url="https://github.com/chinarulezzz/pixload",
        category="other",
        description="Inject payloads into image files.",
        install_cmd="git clone https://github.com/chinarulezzz/pixload",
        run_cmd="perl pixload/pixload.pl {args}",
    ),
    Tool(
        id="sherlock",
        name="Sherlock",
        url="https://github.com/sherlock-project/sherlock",
        category="other",
        description="Hunt down social media accounts by username.",
        install_cmd="pip3 install sherlock-project",
        run_cmd="sherlock {args}",
        reliability="green",
        aliases=["username osint", "social media hunt"],
    ),
    Tool(
        id="social_mapper",
        name="Social Mapper",
        url="https://github.com/Greenwolf/social_mapper",
        category="other",
        description="Find social media accounts by facial recognition.",
        install_cmd="git clone https://github.com/Greenwolf/social_mapper && pip3 install -r social_mapper/requirements.txt",
        run_cmd="python3 social_mapper/social_mapper.py {args}",
    ),
    Tool(
        id="socialscan",
        name="SocialScan",
        url="https://github.com/iojw/socialscan",
        category="other",
        description="Accurately check username and email availability across platforms.",
        install_cmd="pip3 install socialscan",
        run_cmd="socialscan {args}",
        reliability="green",
    ),
    Tool(
        id="tilix",
        name="Tilix (Terminal Multiplexer)",
        url="https://gnunn1.github.io/tilix-web/",
        category="other",
        description="Tiling terminal emulator for Linux.",
        install_cmd="apt-get install -y tilix",
        run_cmd="tilix {args}",
    ),
    Tool(
        id="underhanded",
        name="Application Checker",
        url="https://github.com/jakuta-tech/underhanded",
        category="other",
        description="Check installed application versions for vulnerabilities.",
        install_cmd="git clone https://github.com/jakuta-tech/underhanded",
        run_cmd="python3 underhanded/underhanded.py {args}",
    ),
    Tool(
        id="wifijammer",
        name="WifiJammer-NG",
        url="https://github.com/MisterBianco/wifijammer-ng",
        category="other",
        description="Continuously jam all nearby WiFi clients.",
        install_cmd="git clone https://github.com/MisterBianco/wifijammer-ng && pip3 install -r wifijammer-ng/requirements.txt",
        run_cmd="sudo python3 wifijammer-ng/wifijammer.py {args}",
        flags=["sudo", "hw"],
    ),

    # ================================================================
    # Forenstix-2.0 EXTENDED FORENSICS TOOLS
    # ================================================================

    # ── Memory Forensics ───────────────────────────────────────────────────
    Tool(
        id="avml",
        name="AVML (Azure VM Memory Live)",
        url="https://github.com/microsoft/avml",
        category="mem_forensics",
        description="Portable volatile memory acquisition tool for Linux.",
        install_cmd="curl -sSL https://github.com/microsoft/avml/releases/latest/download/avml -o avml && chmod +x avml",
        run_cmd="sudo ./avml {args}",
        reliability="green",
        flags=["sudo"],
        aliases=["memory dump", "memory acquisition", "ram dump"],
    ),
    Tool(
        id="lime",
        name="LiME (Linux Memory Extractor)",
        url="https://github.com/504ensicsLabs/LiME",
        category="mem_forensics",
        description="Loadable kernel module to acquire volatile memory from Linux.",
        install_cmd="git clone https://github.com/504ensicsLabs/LiME && cd LiME/src && make",
        run_cmd="sudo insmod LiME/src/lime.ko {args}",
        flags=["sudo"],
        aliases=["memory dump", "linux memory acquisition"],
    ),
    Tool(
        id="memprocfs",
        name="MemProcFS",
        url="https://github.com/ufrisk/MemProcFS",
        category="mem_forensics",
        description="Mount a memory dump as a file system — browse processes, files, registry.",
        install_cmd="git clone https://github.com/ufrisk/MemProcFS",
        run_cmd="./MemProcFS/memprocfs {args}",
        reliability="green",
        aliases=["memory analysis", "memory browse"],
    ),
    Tool(
        id="rekall",
        name="Rekall",
        url="https://github.com/google/rekall",
        category="mem_forensics",
        description="Advanced memory forensics framework (Google fork of Volatility).",
        install_cmd="pip3 install rekall",
        run_cmd="rekall {args}",
        aliases=["memory forensics", "memory analysis"],
    ),

    # ── Disk Forensics ─────────────────────────────────────────────────────
    Tool(
        id="dcfldd",
        name="dcfldd",
        url="https://github.com/adulau/dcfldd",
        category="disk_forensics",
        description="Enhanced dd with hashing — the forensic imager standard.",
        install_cmd="apt-get install -y dcfldd",
        run_cmd="dcfldd {args}",
        flags=["sudo"],
        reliability="green",
        aliases=["disk image", "forensic copy"],
    ),
    Tool(
        id="exiftool",
        name="ExifTool",
        url="https://exiftool.org/",
        category="disk_forensics",
        description="Read, write, and edit metadata in files.",
        install_cmd="apt-get install -y exiftool",
        run_cmd="exiftool {args}",
        reliability="green",
        aliases=["metadata", "exif", "file metadata"],
    ),
    Tool(
        id="foremost",
        name="Foremost",
        url="http://foremost.sourceforge.net/",
        category="disk_forensics",
        description="Carve files from disk images by header and footer signatures.",
        install_cmd="apt-get install -y foremost",
        run_cmd="foremost {args}",
        aliases=["file carving", "data recovery"],
    ),
    Tool(
        id="photorec",
        name="PhotoRec",
        url="https://www.cgsecurity.org/wiki/PhotoRec",
        category="disk_forensics",
        description="File data recovery software — works on disks, CD-ROMs, memory cards.",
        install_cmd="apt-get install -y testdisk",
        run_cmd="photorec {args}",
        flags=["interactive"],
        aliases=["file recovery", "data carving"],
    ),
    Tool(
        id="scalpel",
        name="Scalpel",
        url="https://github.com/sleuthkit/scalpel",
        category="disk_forensics",
        description="Fast header/footer-based file carver (faster than Foremost).",
        install_cmd="apt-get install -y scalpel",
        run_cmd="scalpel {args}",
        aliases=["file carving"],
    ),
    Tool(
        id="sleuth_kit",
        name="The Sleuth Kit (TSK)",
        url="https://github.com/sleuthkit/sleuthkit",
        category="disk_forensics",
        description="CLI tools for NTFS/FAT/ext2-4/HFS+ disk image analysis.",
        install_cmd="apt-get install -y sleuthkit",
        run_cmd="fls {args}",
        reliability="green",
        aliases=["filesystem analysis", "disk forensics"],
    ),
    Tool(
        id="testdisk",
        name="TestDisk",
        url="https://www.cgsecurity.org/wiki/TestDisk",
        category="disk_forensics",
        description="Recover lost partitions and repair non-booting disks.",
        install_cmd="apt-get install -y testdisk",
        run_cmd="testdisk {args}",
        flags=["interactive"],
        aliases=["partition recovery", "disk repair"],
    ),

    # ── Network Forensics ──────────────────────────────────────────────────
    Tool(
        id="networkminer",
        name="NetworkMiner",
        url="https://www.netresec.com/index.ashx?page=NetworkMiner",
        category="net_forensics",
        description="Passive network sniffer and packet analyser / NFAT.",
        install_cmd="apt-get install -y networkminer",
        run_cmd="networkminer {args}",
        flags=["gui"],
        aliases=["pcap analysis", "network forensics"],
    ),
    Tool(
        id="suricata",
        name="Suricata",
        url="https://github.com/OISF/suricata",
        category="net_forensics",
        description="High-performance network IDS, IPS, and NSM engine.",
        install_cmd="apt-get install -y suricata",
        run_cmd="suricata {args}",
        flags=["sudo"],
        reliability="green",
        aliases=["ids", "ips", "network detection", "pcap"],
    ),
    Tool(
        id="tcpdump",
        name="tcpdump",
        url="https://www.tcpdump.org/",
        category="net_forensics",
        description="Powerful command-line packet analyser.",
        install_cmd="apt-get install -y tcpdump",
        run_cmd="tcpdump {args}",
        flags=["sudo"],
        reliability="green",
        aliases=["packet capture", "network capture"],
    ),
    Tool(
        id="tshark",
        name="tshark",
        url="https://www.wireshark.org/docs/man-pages/tshark.html",
        category="net_forensics",
        description="Command-line Wireshark — analyse and export PCAP data.",
        install_cmd="apt-get install -y tshark",
        run_cmd="tshark {args}",
        flags=["sudo"],
        reliability="green",
        aliases=["pcap", "wireshark cli"],
    ),
    Tool(
        id="zeek",
        name="Zeek (Bro)",
        url="https://github.com/zeek/zeek",
        category="net_forensics",
        description="Powerful network analysis framework — traffic logs, protocol analysis.",
        install_cmd="apt-get install -y zeek",
        run_cmd="zeek {args}",
        flags=["sudo"],
        reliability="green",
        aliases=["network analysis", "bro", "network monitoring"],
    ),

    # ── Log Analysis & Threat Hunting ──────────────────────────────────────
    Tool(
        id="chainsaw",
        name="Chainsaw",
        url="https://github.com/WithSecureLabs/chainsaw",
        category="log_forensics",
        description="Rapidly hunt through Windows event logs for attack artefacts.",
        install_cmd="cargo install chainsaw",
        run_cmd="chainsaw {args}",
        reliability="green",
        aliases=["windows event logs", "threat hunting", "evtx"],
    ),
    Tool(
        id="hayabusa",
        name="Hayabusa",
        url="https://github.com/Yamato-Security/hayabusa",
        category="log_forensics",
        description="Fast forensics and threat hunting tool for Windows event logs.",
        install_cmd="git clone https://github.com/Yamato-Security/hayabusa && cd hayabusa && cargo build --release",
        run_cmd="./hayabusa/target/release/hayabusa {args}",
        reliability="green",
        aliases=["windows logs", "sigma", "threat hunting"],
    ),
    Tool(
        id="logontracer",
        name="LogonTracer",
        url="https://github.com/JPCERTCC/LogonTracer",
        category="log_forensics",
        description="Investigate malicious Windows logon events via graph visualisation.",
        install_cmd="git clone https://github.com/JPCERTCC/LogonTracer && pip3 install -r LogonTracer/requirements.txt",
        run_cmd="python3 LogonTracer/logontracer.py {args}",
        aliases=["windows logon", "lateral movement detection"],
    ),
    Tool(
        id="loki",
        name="Loki (IOC Scanner)",
        url="https://github.com/Neo23x0/Loki",
        category="log_forensics",
        description="Simple IOC and YARA rule scanner.",
        install_cmd="pip3 install loki",
        run_cmd="python3 loki.py {args}",
        reliability="green",
        aliases=["ioc scan", "yara scan"],
    ),
    Tool(
        id="sigma",
        name="Sigma (sigmac)",
        url="https://github.com/SigmaHQ/sigma",
        category="log_forensics",
        description="Generic signature format for SIEM systems — convert to any query language.",
        install_cmd="pip3 install sigmatools",
        run_cmd="sigmac {args}",
        reliability="green",
        aliases=["siem rules", "detection rules"],
    ),

    # ── Malware Analysis ───────────────────────────────────────────────────
    Tool(
        id="capa",
        name="capa",
        url="https://github.com/mandiant/capa",
        category="malware",
        description="Identify capabilities in PE files — detects ATT&CK techniques.",
        install_cmd="pip3 install flare-capa",
        run_cmd="capa {args}",
        reliability="green",
        aliases=["malware capabilities", "pe analysis", "att&ck"],
    ),
    Tool(
        id="cape",
        name="CAPE Sandbox",
        url="https://github.com/kevoreilly/CAPEv2",
        category="malware",
        description="Malware sandbox with payload extraction (Cuckoo v2 fork).",
        install_cmd="git clone https://github.com/kevoreilly/CAPEv2",
        run_cmd="python3 CAPEv2/utils/submit.py {args}",
        flags=["sudo"],
        aliases=["sandbox", "dynamic analysis", "malware analysis"],
    ),
    Tool(
        id="die",
        name="Detect It Easy (die)",
        url="https://github.com/horsicq/Detect-It-Easy",
        category="malware",
        description="Detect file type and packer/compiler for PE/ELF/Mach-O binaries.",
        install_cmd="apt-get install -y detect-it-easy",
        run_cmd="die {args}",
        reliability="green",
        aliases=["packer detect", "compiler detect", "file type"],
    ),
    Tool(
        id="floss",
        name="FLOSS (FireEye/Mandiant)",
        url="https://github.com/mandiant/flare-floss",
        category="malware",
        description="Automatically de-obfuscate strings from malware binaries.",
        install_cmd="pip3 install flare-floss",
        run_cmd="floss {args}",
        reliability="green",
        aliases=["strings", "de-obfuscate", "malware strings"],
    ),
    Tool(
        id="malduck",
        name="Malduck",
        url="https://github.com/CERT-Polska/malduck",
        category="malware",
        description="Malware analysis toolkit — patterns, crypto, helpers.",
        install_cmd="pip3 install malduck",
        run_cmd="python3 -c \"import malduck; {args}\"",
        reliability="green",
        aliases=["malware analysis"],
    ),
    Tool(
        id="pestudio",
        name="PEstudio (via Wine)",
        url="https://www.winitor.com/",
        category="malware",
        description="Static analysis of executables — indicators, imports, strings.",
        install_cmd="apt-get install -y wine && curl -sSL https://www.winitor.com/download -o pestudio.zip && unzip pestudio.zip",
        run_cmd="wine pestudio/pestudio.exe {args}",
        aliases=["pe analysis", "static analysis"],
    ),
    Tool(
        id="strings",
        name="strings",
        url="https://man7.org/linux/man-pages/man1/strings.1.html",
        category="malware",
        description="Print printable character sequences in a binary file.",
        install_cmd="apt-get install -y binutils",
        run_cmd="strings {args}",
        reliability="green",
        aliases=["binary strings"],
    ),
    Tool(
        id="yara",
        name="YARA",
        url="https://github.com/VirusTotal/yara",
        category="malware",
        description="Pattern matching tool for malware researchers.",
        install_cmd="pip3 install yara-python",
        run_cmd="yara {args}",
        reliability="green",
        aliases=["malware patterns", "ioc matching"],
    ),

    # ── Timeline Analysis ──────────────────────────────────────────────────
    Tool(
        id="log2timeline",
        name="log2timeline / Plaso",
        url="https://github.com/log2timeline/plaso",
        category="timeline",
        description="Auto-extract and parse log and timeline artefacts from disk images.",
        install_cmd="pip3 install plaso",
        run_cmd="log2timeline.py {args}",
        reliability="green",
        aliases=["timeline", "super timeline", "forensic timeline"],
    ),
    Tool(
        id="mactime",
        name="mactime (TSK)",
        url="https://wiki.sleuthkit.org/index.php?title=Mactime",
        category="timeline",
        description="Create timeline from bodyfile output of The Sleuth Kit.",
        install_cmd="apt-get install -y sleuthkit",
        run_cmd="mactime {args}",
        reliability="green",
        aliases=["filesystem timeline"],
    ),
    Tool(
        id="timesketch",
        name="Timesketch",
        url="https://github.com/google/timesketch",
        category="timeline",
        description="Google's collaborative forensic timeline analysis platform.",
        install_cmd="pip3 install timesketch-cli-client",
        run_cmd="timesketch {args}",
        reliability="green",
        flags=["sudo"],
        aliases=["timeline analysis", "forensic timeline"],
    ),
]


# ---------------------------------------------------------------------------
# Index helpers
# ---------------------------------------------------------------------------

def by_id() -> Dict[str, Tool]:
    return {t.id: t for t in TOOLS}


def by_category(cat: str) -> List[Tool]:
    return [t for t in TOOLS if t.category == cat]


def search(query: str) -> List[Tool]:
    """Case-insensitive search across id, name, description, aliases."""
    q = query.lower()
    results = []
    for t in TOOLS:
        if (
            q in t.id.lower()
            or q in t.name.lower()
            or q in t.description.lower()
            or any(q in a.lower() for a in t.aliases)
        ):
            results.append(t)
    return results


def stats() -> Dict[str, int]:
    """Return per-category tool counts."""
    counts: Dict[str, int] = {}
    for t in TOOLS:
        counts[t.category] = counts.get(t.category, 0) + 1
    return counts
